# Generated by Django 5.2.7 on 2025-12-10 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='club',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_form', to='web.post')),
            ],
            options={
                'verbose_name': 'Форма регистрации',
                'verbose_name_plural': 'Формы регистрации',
                'db_table': 'registration_forms',
            },
        ),
        migrations.CreateModel(
            name='RegistrationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('email', 'Email'), ('phone', 'Phone')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='web.registrationform')),
            ],
            options={
                'verbose_name': 'Поле формы регистрации',
                'verbose_name_plural': 'Поля форм регистрации',
                'db_table': 'registration_fields',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='web.registrationform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отправка формы регистрации',
                'verbose_name_plural': 'Отправки форм регистрации',
                'db_table': 'registration_submissions',
            },
        ),
        migrations.CreateModel(
            name='RegistrationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='web.registrationfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='web.registrationsubmission')),
            ],
            options={
                'verbose_name': 'Ответ на поле формы',
                'verbose_name_plural': 'Ответы на поля форм',
                'db_table': 'registration_answers',
            },
        ),
    ]
