# Generated by Django 5.2.7 on 2025-12-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_post_type_alter_club_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='club_avatars/'),
        ),
    ]
