# Generated by Django 5.2.7 on 2025-12-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationprofile',
            options={'verbose_name': 'Профиль организации', 'verbose_name_plural': 'Профили организаций'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Профиль студента', 'verbose_name_plural': 'Профили студентов'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_hash',
        ),
    ]
