# Generated by Django 5.2.7 on 2025-12-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_course_student_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='student',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='student_avatars/'),
        ),
    ]
