"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import importlib.util
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load env from backend/.env when running from repo root.
load_dotenv(dotenv_path=BASE_DIR.parent.parent / ".env", override=False)
load_dotenv(override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-98_lk+4f9g$yv*(n38_yis31@1t1u1!f_gum3z%qv*-w=3t!mc"

# SECURITY WARNING: don't run with debug turned on in production!
SECRET_KEY = os.getenv('SECRET_KEY', 'your-secret-key-here')
DEBUG = os.getenv('DEBUG', 'False') == 'True' #ДЛЯ ПРОДА
# DEBUG = True # ДЛЯ ЛОКАЛ 

ALLOWED_HOSTS = [
    'backend',
    'localhost',
    'hseflow-krutoisashka.amvera.io',
    'hseflowweb-krutoisashka.amvera.io',
    'amvera-krutoisashka-cnpg-pgwebhse-rw',
    "127.0.0.1",
]

# CORS/CSRF settings
# Allow explicit frontend host; allow-all as a fallback to avoid missing origins in prod.
CORS_ALLOWED_ORIGINS = [
    'https://hseflowweb-krutoisashka.amvera.io',
    'https://hseflow-krutoisashka.amvera.io',
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    'https://hseflowweb-krutoisashka.amvera.io',
    'https://hseflow-krutoisashka.amvera.io',
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    'drf_spectacular',
    "users",
    "web",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # must be high to add CORS headers
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        'OPTIONS': {
            'sslmode': 'prefer',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators


# Use custom user with avatar_url while keeping Django auth workflows.
AUTH_USER_MODEL = "users.CustomUser"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_URL = "/media/"
MEDIA_ROOT = "/data/media"

# S3 (S3-compatible, e.g. reg.ru)
USE_S3 = os.getenv("S3_ENABLED", "0") in {"1", "true", "True", "yes", "on"}

if USE_S3:
    _storages_available = importlib.util.find_spec("storages") is not None
    _boto3_available = importlib.util.find_spec("boto3") is not None
    if not (_storages_available and _boto3_available):
        USE_S3 = False

if USE_S3:
    AWS_ACCESS_KEY_ID = os.getenv("S3_ACCESS_KEY_ID") or os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("S3_SECRET_ACCESS_KEY") or os.getenv("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.getenv("S3_BUCKET") or os.getenv("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = os.getenv("S3_ENDPOINT_URL")
    AWS_S3_REGION_NAME = os.getenv("S3_REGION") or os.getenv("AWS_DEFAULT_REGION") or "us-east-1"

    AWS_S3_ADDRESSING_STYLE = os.getenv("S3_ADDRESSING_STYLE", "path")
    AWS_S3_SIGNATURE_VERSION = os.getenv("S3_SIGNATURE_VERSION", "s3v4")

    _s3_verify = (os.getenv("S3_VERIFY") or "").strip()
    if _s3_verify.lower() in {"0", "false", "no", "off"}:
        AWS_S3_VERIFY = False
    elif _s3_verify:
        AWS_S3_VERIFY = _s3_verify

    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = os.getenv("S3_QUERYSTRING_AUTH", "1") not in {"0", "false", "False", "no", "off"}
    AWS_S3_FILE_OVERWRITE = False

    S3_CUSTOM_DOMAIN = os.getenv("S3_CUSTOM_DOMAIN")
    if S3_CUSTOM_DOMAIN and not AWS_QUERYSTRING_AUTH:
        AWS_S3_CUSTOM_DOMAIN = S3_CUSTOM_DOMAIN

    if "storages" not in INSTALLED_APPS:
        INSTALLED_APPS += ["storages"]

    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT authentication via djangorestframework-simplejwt
from datetime import timedelta

REST_FRAMEWORK.update({
    'DEFAULT_AUTHENTICATION_CLASSES': (
        ('rest_framework_simplejwt.authentication.JWTAuthentication',)
        + (
            ('rest_framework.authentication.SessionAuthentication',)
            if DEBUG
            else tuple()
        )
    ),
})

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "API",
    "DESCRIPTION": "API documentation",
    "VERSION": "0.0.1",
    "SERVE_INCLUDE_SCHEMA": True,
    "deepLinking": True,
}
